### ISSUE TITLE
Starting new game in middle of game is too easy to do accidentally

### ISSUE THREAD

**Issue by dperelman** [dperelman/codenames.plus#10]
Currently there's no confirmation on starting a new game, even if the game has already started. Suggested UI: if the game has not started (i.e. no cards flipped and no clues given), then the new game button works same as currently. Otherwise show a warning and require all players to click it?

**Comment by SayantaBhar** [comment]
A simple ok-cancel alert in case the game is not over should be sufficient I think.

**Comment by SayantaBhar** [comment]
https://github.com/dperelman/codenames.plus/pull/14
