### ISSUE TITLE
Feature request: Colorblindness support

### ISSUE THREAD

**Issue by rohitu** [dperelman/codenames.plus#15]
Change color scheme to support colorblindness or vision-impaired people. At minimum, we could run the colors through the WebAIM contrast checker: https://webaim.org/resources/contrastchecker/ and tweak as needed

Edit: We could also add non-color based markers (different borders, icons, etc) to indicate a card was selected and whether it's red/blue/neutral.

**Comment by dperelman** [comment]
87e713d adds background textures to the red/blue tiles. I think that solves this issue. The other color differences are fairly different in shade, but it's possible it would help to add textures to distinguish them as well.

**Comment by dperelman** [comment]
BTW, in [feature/colorblind-decorated-edges](https://github.com/dperelman/codenames.plus/tree/feature/colorblind-decorated-edges), I tried to use border decorations instead, and it didn't work very well. But it may have been a poor choice of decoration styles.
