### ISSUE TITLE
Add player icons to each card to indicate votes in consensus mode

### ISSUE THREAD

**Issue by rohitu** [dperelman/codenames.plus#16]
Add player icons to each card to indicate votes in consensus mode. If there are a lot of players, we could show at most 4 or 5 and add some sort of flyout or dialog for expanding the list, and also include some sort of numerical count to indicate votes remaining.

**Comment by dperelman** [comment]
a6c6c7f53d94382a8924fcc7ba8e84ddb20da5a9 adds a 🤔 (thinking face emoji) on the tile for each player who has guessed that tile, in addition to highlighting the tile a bit more clearly.

It does not identify which players (there isn't really space for that... maybe it could be in a tooltip?) or how many more are needed. I'm not sure how much those would help given you can just look at the player list.
